In [3]:
import pandas as pd
df = pd.read_csv("trafico_historico.csv", sep=";")
df.head()

,Año,Mes,Cod_Operador,Operador,Grupo,ORIG_1,DEST_1,ORIG_1_N,DEST_1_N,ORIG_1_PAIS,...,ORIG_2_PAIS,DEST_2_PAIS,OPER_2,NAC,PAX_LIB,PASAJEROS,CAR_LIB,CARGA (Ton),CORREO,Distancia
0,1984,1,31,FAST AIR,FAST AIR,ARI,NYC,ARICA,NEW YORK,CHILE,...,CHILE,ESTADOS UNIDOS,SALEN,INTERNACIONAL,0.0,0.0,0.0,13.094,0.0,7369.0
1,1984,1,31,FAST AIR,FAST AIR,SCL,BOG,SANTIAGO,BOGOTA,CHILE,...,CHILE,COLOMBIA,SALEN,INTERNACIONAL,0.0,0.0,0.0,29.086,0.0,4247.0
2,1984,1,31,FAST AIR,FAST AIR,SCL,MIA,SANTIAGO,MIAMI,CHILE,...,CHILE,ESTADOS UNIDOS,SALEN,INTERNACIONAL,0.0,0.0,0.0,33.627,0.0,6653.0
3,1984,1,31,FAST AIR,FAST AIR,SCL,PTY,SANTIAGO,CIUDAD DE PANAMÁ,CHILE,...,CHILE,PANAMA,SALEN,INTERNACIONAL,0.0,0.0,0.0,0.000,0.0,4805.0
4,1984,1,31,FAST AIR,FAST AIR,SCL,SAO,SANTIAGO,SAO PAULO,CHILE,...,CHILE,BRASIL,SALEN,INTERNACIONAL,0.0,0.0,0.0,62.002,0.0,2585.0

In [5]:

columnas_muestra = [
    "Año",
    "Mes",
    "Operador",
    "ORIG_1_N",
    "DEST_1_N",
    "NAC",
    "PASAJEROS",
    "Distancia"
]

año_reciente = df["Año"].max()

muestra = df[
    (df["Año"] == año_reciente) &
    (df["PASAJEROS"] > 0)
]

muestra[columnas_muestra].head()

,Año,Mes,Operador,ORIG_1_N,DEST_1_N,NAC,PASAJEROS,Distancia
240546,2024,1,AIR CANADA,TORONTO,SANTIAGO,INTERNACIONAL,5594.0,8674.0
240547,2024,1,BRITISH AIRWAYS,LONDRES,SANTIAGO,INTERNACIONAL,3388.0,11663.0
240548,2024,1,KLM,AMSTERDAM,SANTIAGO,INTERNACIONAL,2319.0,12000.0
240551,2024,1,DELTA AIRLINES,ATLANTA,SANTIAGO,INTERNACIONAL,9049.0,7832.0
240552,2024,1,AMERICAN AIRLINES,DALLAS,SANTIAGO,INTERNACIONAL,5632.0,8035.0

In [ ]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251117 entries, 0 to 251116
Data columns (total 25 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Año           251117 non-null  int64
 1   Mes           251117 non-null  int64
 2   Cod_Operador  251117 non-null  object
 3   Operador      251117 non-null  object
 4   Grupo         251117 non-null  object
 5   ORIG_1        251117 non-null  object
 6   DEST_1        251117 non-null  object
 7   ORIG_1_N      251115 non-null  object
 8   DEST_1_N      251113 non-null  object
 9   ORIG_1_PAIS   251115 non-null  object
 10  DEST_1_PAIS   251113 non-null  object
 11  ORIG_2        251117 non-null  object
 12  DEST_2        251117 non-null  object
 13  ORIG_2_N      251117 non-null  object
 14  DEST_2_N      251111 non-null  object
 15  ORIG_2_PAIS   251117 non-null  object
 16  DEST_2_PAIS   251111 non-null  object
 17  OPER_2        251117 non-null  object
 18  NAC           251117 non-null  object
 19  PAX_LIB       194055 non-null  float64
 20  PASAJEROS     251117 non-null  int64
 21  CAR_LIB       251117 non-null  float64
 22  CARGA (Ton)   251117 non-null  float64
 23  CORREO        194055 non-null  float64
 24  Distancia     251117 non-null  int64
dtypes: float64(4), int64(4), object(17)
memory usage: 47.9+ MB

# Pasajeros por año

In [ ]:
df.groupby("Año")["PASAJEROS"].sum()

Año
1984     1110351
1985     1118493
1986     1210326
1987     1406707
1988     1605303
1989     1764728
1990     1909311
1991     2111226
1992     2500489
1993     3033946
1994     3678561
1995     4221439
1996     4823373
1997     5961943
1998     6367271
1999     6342805
2000     6402596
2001     6247474
2002     5932956
2003     6319234
2004     6618872
2005     7222336
2006     7610583
2007     9010979
2008     9709025
2009     9711882
2010    11064487
2011    12989318
2012    15233980
2013    16476447
2014    17241299
2015    18153542
2016    20088333
2017    22316092
2018    24541998
2019    26086612
2020     9404620
2021    11201843
2022    20338277
2023    24930759
2024    28169121
2025    28386490
Name: PASAJEROS, dtype: int64

# Pasajeros por Operador

In [ ]:
df.groupby("Operador")["PASAJEROS"].sum().sort_values(ascending=False).head(10)

Operador
LATAM AIRLINES GROUP     157909353
LATAM AIRLINES CHILE      81116183
SKY                       57655726
JETSMART                  19643798
LADECO                    14708616
LATAM AIRLINES BRASIL      8915413
AMERICAN AIRLINES          7767373
COPA                       7359373
AEROLINEAS ARGENTINAS      7083884
IBERIA                     6230817
Name: PASAJEROS, dtype: int64

# Pasajeros por mes

In [ ]:
df.groupby("Mes")["PASAJEROS"].sum()

Mes
1     42950923
2     40344095
3     35969034
4     30636002
5     30859030
6     29821780
7     37079445
8     34335075
9     34392969
10    36753207
11    37737657
12    39696210
Name: PASAJEROS, dtype: int64

# Destinos con mayor cantidad de Pasajeros

In [ ]:
top_destinos = (
    df.groupby("DEST_1_N")["PASAJEROS"]
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

top_destinos

DEST_1_N
SANTIAGO        199325026
ANTOFAGASTA      19682571
BUENOS AIRES     17754302
PUERTO MONTT     16429728
IQUIQUE          15183439
Name: PASAJEROS, dtype: int64